config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' 
  resources :personas  
  resources :vehiculos  

end

app/models/persona.rb
class Persona < ActiveRecord::Base
end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  
  def index
    @personas = Persona.all
  end
  
  def show
    @persona = Persona.find(params[:id])   
  end
  
  def new
    @persona = Persona.new
  end
  
  def create
    @persona = Persona.new(persona_params)
    if @persona.save
       redirect_to personas_path
    else
       render :new
    end 
    
    
  end
  
  def destroy

    @persona = Persona.find(params[:id])
    @persona.destroy 
    redirect_to personas_path
  end
  
  
  def edit
    @persona = Persona.find(params[:id])
  end
  
  def update
    @persona = Persona.find(params[:id])
    if @persona.update(persona_params)
      redirect_to persona_path(@persona.id)
    else
      render :edit
    end
  end
  
  #strong params
  private
    def persona_params
      params.require(:persona).permit(:nombre, :edad, :apellido, :email)
    end
  
end

app/controllers/vehiculos_controller.rb
class VehiculosController < ApplicationController
  def index
    @vehiculos = Vehiculo.all
  end
  
  def show
    @vehiculo = Vehiculo.find(params[:id])   
  end
  
  def new
    @vehiculo = Vehiculo.new
  end
  
  def create
    @vehiculo = Vehiculo.new(vehiculo_params)
    if @vehiculo.save
       redirect_to vehiculos_path
    else
       render :new
    end 
    
    
  end
  
  def destroy

    @vehiculo = Vehiculo.find(params[:id])
    @vehiculo.destroy 
    redirect_to vehiculos_path
  end
  
  
  def edit
    @vehiculo = Vehiculo.find(params[:id])
  end
  
  def update
    @vehiculo = Vehiculo.find(params[:id])
    if @vehiculo.update(vehiculo_params)
      redirect_to vehiculo_path(@vehiculo.id)
    else
      render :edit
    end
  end
  
  #strong params
  private
    def vehiculo_params
      params.require(:vehiculo).permit(:marca)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
    def form_title
        @persona.new_record? ? "Nueva Persona" : "Editar Persona"
    end    

end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
    def form_title_v
        @vehiculo.new_record? ? "Nueva Vehiculo" : "Editar Vehiculo"
    end  
end

app/views/home/index.html.erb
<h2>Transito </h2>

<%= link_to "Vehiculos", vehiculos_path %>
<%= link_to "Personas", personas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/personas/_form.html.erb
<h1><%= form_title %></h1>

<%= form_for @persona do |f| %>
  
  
    <div>
        <%= f.label :nombre %>
        <%= f.text_field :nombre %>
    </div>
    <div>
        <%= f.label :apellido %>
         <%= f.text_field :apellido %>
    </div>
    
    <div>
        <%= f.label :email %>
        <%= f.email_field :email %>
    </div>
    
    <div>
        <%= f.label :edad %>
      <%= f.number_field :edad %>
    </div>
    
    <div>
      <%= f.submit form_title, class: "btn btn-info" %>
    </div>

<% end %>

app/views/personas/edit.html.erb
<h1>Editar persona</h1>
<%= render 'form' %>
    
  

app/views/personas/index.html.erb
<h1>Personas</h1>
<table border=1>
    
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>View</th>
        </tr>
    </thead>
    <tbody>
        
<% @personas.each do |persona| %>
       <tr>
            <td><%= persona.id %> </td>
            <td><%= persona.nombre %> </td>
            <td><%= persona.apellido %></td>
            <td><%= link_to "V" , persona_path(persona) %>  </td>
  
       </tr>
    
<% end %>

    </tbody>

</table>

<div>
    <%= link_to "Crear Persona",  new_persona_path %>
</div>

app/views/personas/new.html.erb
<h1>Crear una nueva persona</h1>
<%= render 'form' %>

app/views/personas/show.html.erb
<h2> <%=@persona.nombre %>  <%= @persona.apellido%>  </h2>

<div>
    <span>Edad: </span> <%= @persona.edad %>

</div>

<div>
    <span>E-mail </span> <%= @persona.email %>
    
</div>

<div>
    <%= link_to "volver", root_path  %> 
</div>
<div>
    <%= link_to "Editar", edit_persona_path(@persona) %>
</div>

<div>
    <%= link_to "Eliminar", @persona , method: :delete, data: { confirm: "¿Estas seguro?" } %>
</div>

app/views/vehiculos/_form.html.erb
<h1><%= form_title_v %></h1>

<%= form_for @vehiculo do |f| %>
  
  
    <div>
        <%= f.label :marca %>
        <%= f.text_field :marca %>
    </div>

    
    <div>
      <%= f.submit form_title_v, class: "btn-pink" %>
    </div>

<% end %>

app/views/vehiculos/edit.html.erb
<h1>Editar vehiculo</h1>
<%= render 'form' %>

app/views/vehiculos/index.html.erb
<h1>Vehiculos</h1>
<table border=1>
    
    <thead>
        <tr>
            <th>Id</th>
            <th>Marca</th>
            <th>View</th>
        </tr>
    </thead>
    <tbody>
        
<% @vehiculos.each do |vehiculo| %>
       <tr>
            <td><%= vehiculo.id %> </td>
            <td><%= vehiculo.marca %> </td>
            <td><%= link_to "V" , vehiculo_path(vehiculo) %>  </td>
  
       </tr>
    
<% end %>

    </tbody>

</table>

<div>
    <%= link_to "Crear Vehiculo",  new_vehiculo_path %>
</div>

app/views/vehiculos/new.html.erb
<%= render 'form' %>

app/views/vehiculos/show.html.erb
<h2> <%=@vehiculo.marca %>   </h2>


<div>
    <%= link_to "volver", vehiculos_path  %> 
</div>
<div>
    <%= link_to "Editar", edit_vehiculo_path(@vehiculo), class: "btn-pink" %>
</div>

<div>
    <%= link_to "Eliminar", @vehiculo , method: :delete, data: { confirm: "¿Estas seguro?" } %>
</div>